# Generated by Django 4.1.4 on 2023-01-01 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100, unique=True)),
                ('project_descr', models.TextField(blank=True, max_length=300)),
                ('project_prog_percent', models.IntegerField(default=0)),
                ('project_finish_date', models.DateField(blank=True)),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100, unique=True)),
                ('task_descr', models.TextField(blank=True, max_length=300)),
                ('task_prog_percent', models.IntegerField(default=0)),
                ('is_Completed', models.BooleanField(default=False)),
                ('task_finish_date', models.DateField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.projects')),
                ('task_tags', models.ManyToManyField(blank=True, to='core.tags')),
            ],
        ),
        migrations.AddField(
            model_name='tags',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.tasks'),
        ),
    ]
