# Generated by Django 4.1.4 on 2023-01-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projects_tags_tasks_tags_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_prog_percent',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
