# Generated by Django 4.1.4 on 2023-01-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tags_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_tasks',
            field=models.ManyToManyField(related_name='projects', to='core.tasks'),
        ),
    ]
