# Generated by Django 4.1.4 on 2023-01-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projects_project_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=50),
        ),
    ]
