# Generated by Django 4.1.4 on 2023-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_tasks_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_title',
            field=models.CharField(max_length=100),
        ),
    ]
