# Generated by Django 4.1.4 on 2023-01-03 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tasks_task_owner_alter_projects_project_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_tasks',
            field=models.ManyToManyField(blank=True, related_name='task', to='core.tasks'),
        ),
    ]
