# Generated by Django 4.1.4 on 2023-01-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_projects_project_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='core.tasks'),
        ),
    ]
