# Generated by Django 4.1.4 on 2023-01-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_projects_project_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_owner',
        ),
        migrations.AddField(
            model_name='tasks',
            name='parent_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
            preserve_default=False,
        ),
    ]
