# Generated by Django 4.1.4 on 2023-01-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_tasks_task_owner_tasks_parent_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
        ),
    ]
