# Generated by Django 4.1.4 on 2023-01-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_projects_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='parent_project',
        ),
        migrations.AddField(
            model_name='tasks',
            name='parent_project',
            field=models.ManyToManyField(blank=True, null=True, to='core.projects'),
        ),
    ]
