# Generated by Django 4.1.4 on 2023-01-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_tasks_parent_project_tasks_parent_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='parent_project',
            field=models.ManyToManyField(blank=True, to='core.projects'),
        ),
    ]
