# Generated by Django 4.1.4 on 2023-01-03 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_projects_project_owner_alter_tasks_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_tasks',
        ),
        migrations.AddField(
            model_name='tasks',
            name='parent_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
            preserve_default=False,
        ),
    ]
