# Generated by Django 4.1.4 on 2023-01-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_projects_project_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projects_tasks',
            field=models.ManyToManyField(blank=True, to='core.tasks'),
        ),
    ]
