# Generated by Django 4.1.4 on 2023-01-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_projects_projects_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projects_tasks',
        ),
    ]
