# Generated by Django 4.1.4 on 2023-01-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_projects_projects_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='is_Completed',
        ),
    ]
